default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: 'active_codhab_development'
  username: 'postgres'
  password: <%= ENV['DB_PASS'] %>
  host: 'localhost'
  schema_search_path: 'extranet, sihab, portal, generic'

test:
  <<: *default
  database: 'active_codhab_test'
  username: 'postgres'
  password: <%= ENV['DB_PASS'] %>
  host: 'localhost'
  schema_search_path: 'extranet, sihab, portal, generic'
